//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Arma3BEService.Lib.ModelCompact
{
    public partial class Note
    {

        public Note()
        {
            Id = Guid.NewGuid();
            Date = DateTime.UtcNow;
        }

        [Key]
        public System.Guid Id { get; set; }
        public System.Guid PlayerId { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }

        [ForeignKey("PlayerId")]
        public virtual Player Player { get; set; }
    }
}
