//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Arma3BEService.Lib.ModelCompact
{
    public partial class ServerInfo : Server
    {
        public ServerInfo()
        {
            this.ChatLog = new HashSet<ChatLog>();
            this.PlayerHistory = new HashSet<PlayerHistory>();
            this.Admins = new HashSet<Admin>();
        }




        public virtual ICollection<ChatLog> ChatLog { get; set; }

        public virtual ICollection<Ban> Bans { get; set; }

        public virtual ICollection<Admin> Admins { get; set; }

        public virtual ICollection<PlayerHistory> PlayerHistory { get; set; }
    }

    public class Server : ServerBase
    {
        [Required]
        public string Host { get; set; }

        [Required]
        public int Port { get; set; }

        [Required]
        public string Password { get; set; }
    }

    public class ServerBase
    {
        [Key]
        public System.Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public bool Active { get; set; }
    }
}
