//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma3BEService.TestClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/Arma3BEClient.Updater.Models")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerBase", Namespace="http://schemas.datacontract.org/2004/07/Arma3BEService.Lib.ModelCompact")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Arma3BEService.TestClient.ServiceReference1.Server))]
    public partial class ServerBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Server", Namespace="http://schemas.datacontract.org/2004/07/Arma3BEService.Lib.ModelCompact")]
    [System.SerializableAttribute()]
    public partial class Server : Arma3BEService.TestClient.ServiceReference1.ServerBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PortField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Host {
            get {
                return this.HostField;
            }
            set {
                if ((object.ReferenceEquals(this.HostField, value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Port {
            get {
                return this.PortField;
            }
            set {
                if ((this.PortField.Equals(value) != true)) {
                    this.PortField = value;
                    this.RaisePropertyChanged("Port");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Arma3BEService", ConfigurationName="ServiceReference1.IArma3ServiceContract", CallbackContract=typeof(Arma3BEService.TestClient.ServiceReference1.IArma3ServiceContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IArma3ServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/Join", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/JoinResponse")]
        void Join();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/Join", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/JoinResponse")]
        System.Threading.Tasks.Task JoinAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "e", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "eResponse")]
        int SendChatMessage(Arma3BEService.TestClient.ServiceReference1.ChatMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "e", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "eResponse")]
        System.Threading.Tasks.Task<int> SendChatMessageAsync(Arma3BEService.TestClient.ServiceReference1.ChatMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "ver", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "verResponse")]
        Arma3BEService.TestClient.ServiceReference1.ServerBase AddOrUpdateServer(Arma3BEService.TestClient.ServiceReference1.Server server);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "ver", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "verResponse")]
        System.Threading.Tasks.Task<Arma3BEService.TestClient.ServiceReference1.ServerBase> AddOrUpdateServerAsync(Arma3BEService.TestClient.ServiceReference1.Server server);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServers", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServersResp" +
            "onse")]
        Arma3BEService.TestClient.ServiceReference1.ServerBase[] GetServers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServers", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServersResp" +
            "onse")]
        System.Threading.Tasks.Task<Arma3BEService.TestClient.ServiceReference1.ServerBase[]> GetServersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArma3ServiceContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/Message")]
        void Message([System.ServiceModel.MessageParameterAttribute(Name="message")] Arma3BEService.TestClient.ServiceReference1.ChatMessage message1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArma3ServiceContractChannel : Arma3BEService.TestClient.ServiceReference1.IArma3ServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Arma3ServiceContractClient : System.ServiceModel.DuplexClientBase<Arma3BEService.TestClient.ServiceReference1.IArma3ServiceContract>, Arma3BEService.TestClient.ServiceReference1.IArma3ServiceContract {
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join() {
            base.Channel.Join();
        }
        
        public System.Threading.Tasks.Task JoinAsync() {
            return base.Channel.JoinAsync();
        }
        
        public int SendChatMessage(Arma3BEService.TestClient.ServiceReference1.ChatMessage message) {
            return base.Channel.SendChatMessage(message);
        }
        
        public System.Threading.Tasks.Task<int> SendChatMessageAsync(Arma3BEService.TestClient.ServiceReference1.ChatMessage message) {
            return base.Channel.SendChatMessageAsync(message);
        }
        
        public Arma3BEService.TestClient.ServiceReference1.ServerBase AddOrUpdateServer(Arma3BEService.TestClient.ServiceReference1.Server server) {
            return base.Channel.AddOrUpdateServer(server);
        }
        
        public System.Threading.Tasks.Task<Arma3BEService.TestClient.ServiceReference1.ServerBase> AddOrUpdateServerAsync(Arma3BEService.TestClient.ServiceReference1.Server server) {
            return base.Channel.AddOrUpdateServerAsync(server);
        }
        
        public Arma3BEService.TestClient.ServiceReference1.ServerBase[] GetServers() {
            return base.Channel.GetServers();
        }
        
        public System.Threading.Tasks.Task<Arma3BEService.TestClient.ServiceReference1.ServerBase[]> GetServersAsync() {
            return base.Channel.GetServersAsync();
        }
    }
}
