// <auto-generated />
namespace Arma3BEClient.ServiceCore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _2015_05_10_20_17 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2015_05_10_20_17));
        
        string IMigrationMetadata.Id
        {
            get { return "201505101518515_2015_05_10_20_17"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
