//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arma3BEService.Core.SelfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Arma3BEService", ConfigurationName="SelfServiceReference.IArma3ServiceContract", CallbackContract=typeof(Arma3BEService.Core.SelfServiceReference.IArma3ServiceContractCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IArma3ServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "e", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "eResponse")]
        int SendChatMessage(Arma3BEClient.Updater.Models.ChatMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "e", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/SendChatMessag" +
            "eResponse")]
        System.Threading.Tasks.Task<int> SendChatMessageAsync(Arma3BEClient.Updater.Models.ChatMessage message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "ver", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "verResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Arma3BEService.Lib.ModelCompact.Server))]
        Arma3BEService.Lib.ModelCompact.ServerBase AddOrUpdateServer(Arma3BEService.Lib.ModelCompact.Server server);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "ver", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/AddOrUpdateSer" +
            "verResponse")]
        System.Threading.Tasks.Task<Arma3BEService.Lib.ModelCompact.ServerBase> AddOrUpdateServerAsync(Arma3BEService.Lib.ModelCompact.Server server);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServers", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServersResp" +
            "onse")]
        Arma3BEService.Lib.ModelCompact.ServerBase[] GetServers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServers", ReplyAction="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/GetServersResp" +
            "onse")]
        System.Threading.Tasks.Task<Arma3BEService.Lib.ModelCompact.ServerBase[]> GetServersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArma3ServiceContractCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://Microsoft.ServiceModel.Arma3BEService/IArma3ServiceContract/Message")]
        void Message([System.ServiceModel.MessageParameterAttribute(Name="message")] Arma3BEClient.Updater.Models.ChatMessage message1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IArma3ServiceContractChannel : Arma3BEService.Core.SelfServiceReference.IArma3ServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Arma3ServiceContractClient : System.ServiceModel.DuplexClientBase<Arma3BEService.Core.SelfServiceReference.IArma3ServiceContract>, Arma3BEService.Core.SelfServiceReference.IArma3ServiceContract {
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public Arma3ServiceContractClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public int SendChatMessage(Arma3BEClient.Updater.Models.ChatMessage message) {
            return base.Channel.SendChatMessage(message);
        }
        
        public System.Threading.Tasks.Task<int> SendChatMessageAsync(Arma3BEClient.Updater.Models.ChatMessage message) {
            return base.Channel.SendChatMessageAsync(message);
        }
        
        public Arma3BEService.Lib.ModelCompact.ServerBase AddOrUpdateServer(Arma3BEService.Lib.ModelCompact.Server server) {
            return base.Channel.AddOrUpdateServer(server);
        }
        
        public System.Threading.Tasks.Task<Arma3BEService.Lib.ModelCompact.ServerBase> AddOrUpdateServerAsync(Arma3BEService.Lib.ModelCompact.Server server) {
            return base.Channel.AddOrUpdateServerAsync(server);
        }
        
        public Arma3BEService.Lib.ModelCompact.ServerBase[] GetServers() {
            return base.Channel.GetServers();
        }
        
        public System.Threading.Tasks.Task<Arma3BEService.Lib.ModelCompact.ServerBase[]> GetServersAsync() {
            return base.Channel.GetServersAsync();
        }
    }
}
